#!/bin/bash

set -eo pipefail

xcodebuild \
  -project RecurlySDK-iOS.xcodeproj \
  -scheme RecurlySDK-iOS \
  -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
  PUBLIC_KEY=$API_TOKEN \
  test
