name: deploy_to_cocoapods
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Check version consistency
      run: scripts/check_version.sh
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app && /usr/bin/xcodebuild -version
    - name: List Simulators
      run: xcrun simctl list runtimes      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=${TAG_NAME#v}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
