name: deploy_to_cocoapods

on:
  release:
    types: [released]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version  
    - name: List Simulators
      run: xcrun simctl list runtimes      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        export LIB_VERSION=${VERSION:1:6}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
